<?php
/**
 * @file
 * Code for the Juraport base feature.
 */

include_once 'juraport_base.features.inc';

/**
 * Implements hook_date_formats().
 */
function juraport_base_date_formats() {
  return array(
    array(
      'type' => 'short',
      'format' => 'j. M Y - G:i',
      'locales' => array(''),
    ),
    array(
      'type' => 'juraport_date_only',
      'format' => 'l j. F',
      'locales' => array(),
    ),
    array(
      'type' => 'juraport_time_only',
      'format' => 'G:i',
      'locales' => array(),
    ),
  );
}

/**
 * Implements hook_date_format_types().
 */
function juraport_base_date_format_types() {
  return array(
    'juraport_date_only' => t('Juraport date only'),
    'juraport_time_only' => t('Juraport time only'),
  );
}

/**
 * Define site roles in code.
 *
 * @return
 *   An array defining all the roles for the site.
 */
function juraport_base_secure_permissions_roles() {
  return array(
    'anonymous user',
    'authenticated user',
    'juraport editor',
  );
}

/**
 * Define site permissions in code.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return
 *   An array defining all the permissions for the site.
 */
function juraport_base_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'access content',
      'search content',
    ),
    'authenticated user' => array(
      'access content',
      'search content',
    ),
    'juraport editor' => array(
      'access administration menu',
      'access administration pages',
      'access content',
      'access content overview',
      'access contextual links',
      'access overlay',
      'access site in maintenance mode',
      'edit any jura_subject content',
      'edit own juraport_editor profile',
      'edit own jura_subject content',
      'edit any page content',
      'edit own page content',
      'search content',
      'use advanced search',
      'view own unpublished content',
      'view revisions',
      'view the administration theme',
      'use text format filtered_html',
    ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_preprocess_html().
 */
function juraport_base_preprocess_html(&$variables) {
  // If this is a search: Add meta-tags for webtrends on-site search.
  if (arg(0) == 'search' && $search_query = arg(2)) {
    // Take a peak at the pager to get the search count
    $search_count = $GLOBALS['pager_total_items'][0];
    // Add the meta-tags
    $meta_tag['#tag'] = 'meta';
    $meta_tag['#attributes'] = array(
      'name' => 'WT.oss',
      'content' => check_plain($search_query),
    );
    drupal_add_html_head($meta_tag, 'search_query_meta_tag');
    $meta_tag['#attributes'] = array(
      'name' => 'WT.oss_r',
      'content' => $search_count,
    );
    drupal_add_html_head($meta_tag, 'search_count_meta_tag');
  }
}

/**
 * Implements hook_page_build().
 */
function juraport_base_page_build(&$page) {
  $html = '<img alt="dcsimg" id="dcsimg" width="1" height="1" src="//statse.webtrendslive.com/dcs2221gkzn196tf2ood4s62q_3z8l/njs.gif?dcsuri=/nojavascript&amp;WT.js=No&amp;WT.tv=10.4.1&amp;dcssip=www.juraport.dk"/>';
  $page['page_bottom']['webtrends'] = array(
    '#prefix' => '<noscript>',
    '#suffix' => '</noscript>',
    '#markup' => $html,
  );
}
